name: Docker Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: | 
        docker-compose build
        docker-compose pull
        docker ps -a
        
    - name: Run Tests
      run: | 
        docker-compose up -d zookeeper kafka
        docker-compose up --exit-code-from=subscriptions-test subscriptions-test
